name: Pipeline Python

on:
  push:
    branches:
      - main

jobs:
  teste-soma:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar pytest
        run: pip install pytest

      - name: Executar teste de soma
        run: pytest test_app.py::test_soma


  teste-subtracao:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar pytest
        run: pip install pytest

      - name: Executar teste de subtração
        run: pytest test_app.py::test_subtracao


  teste-multiplicacao:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar pytest
        run: pip install pytest

      - name: Executar teste de multiplicação
        run: pytest test_app.py::test_multiplicacao


  teste-divisao:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar pytest
        run: pip install pytest

      - name: Executar teste de divisão
        run: pytest test_app.py::test_divisao