name: Primeira Pipeline
on:
    push:
        branches: [main]
jobs:
    teste:
        run-on: ubuntu-lastet
            
        steps:
           -name: Baixar Código do Repositório
            uses: actions/checkout@v4

    